add authorization
Employee-s-file-cabinet/backend pull request #12
Opened 2023-12-16 10:13 UTC by kathgod

2023-12-16 12:20 UTC, Karzoug requested changes
Комментарии написал. 
Надо бы разобраться с отличием аутентификации и авторизации. Авторизации здесь нет. 
Много магических чисел/строк - вынести бы в константы/переменные пакета, в котором они определены.

2023-12-16 12:20 UTC, Karzoug commented on internal/logic/authorization.go
> +func LogicAuthorization(r *http.Request, auth api.Auth) (int, ResponceToken) {
Стиль: это C-стиль возврата из функции - мы ждем некоторого числового кода, который может говорить об ошибке. В go так обычно не пишут. Для этого общепринято делать так: (token, error).

2023-12-16 12:20 UTC, Karzoug commented on internal/logic/authorization.go
> +	rows, err := db.Query("SELECT password_hash FROM authorizations WHERE username = $1", auth.Login)
Не используется контекст (критично). 
Мы знаем, что возвращается максимум один результат - для этого есть функция [QueryRowContext](https://pkg.go.dev/database/sql#DB.QueryRowContext)

2023-12-16 12:20 UTC, Karzoug commented on internal/logic/authentication.go
> +		log.Println(err)
Пропущен return?

2023-12-16 12:20 UTC, Karzoug commented on internal/logic/authentication.go
> +	// Вывод информации из токена
А зачем весь код ниже verifyPasetoToken?

2023-12-16 12:20 UTC, Karzoug commented on internal/logic/authentication.go
> +	byteToken, err := io.ReadAll(r.Body)
Токен приходит в заголовке AUTHORIZATION, мы никогда не будем читать его из тела запроса.

2023-12-16 12:20 UTC, Karzoug commented on internal/app/handler
> +func (s *server) Authorization(w http.ResponseWriter, r *http.Request) {
Авторизация должна стать middleware, а не handler.

2023-12-16 12:20 UTC, Karzoug commented on internal/app/handler
> +	json.NewEncoder(w).Encode(response)
Проверить возвращаемую ошибку.

2023-12-16 14:21 UTC, PaulYakow requested changes

2023-12-16 14:21 UTC, PaulYakow commented on internal/logic/authorization.go
> +	"github.com/Employee-s-file-cabinet/backend/internal/server/internal/api"
[critical] Импорт есть, а пакета физически в ветке нет - ошибка компиляции.

2023-12-16 16:00 UTC, kathgod commented on internal/app/handler
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Не поняла, что конкретно требуется ему тогда вернуть во время ошибки.

2023-12-16 16:01 UTC, kathgod commented on internal/logic/authorization.go
> +	expirationTime := time.Now().Add(1 * time.Hour)
На сколько по времени увеличиваем?

2023-12-16 16:02 UTC, kathgod commented on internal/logic/authentication.go
> +	// Вывод информации из токена
Объянить что он делает?

2023-12-16 16:03 UTC, kathgod commented on internal/app/handler
> +func (s *server) Authorization(w http.ResponseWriter, r *http.Request) {
1) Что подразумевается под проверкой авторизации пользователя.
2) На сколько необходимо на стадии mvp переделывать handler в middleware

2023-12-16 16:03 UTC, kathgod commented on internal/app/handler
> +	json.NewEncoder(w).Encode(response)
Где?

2023-12-16 16:06 UTC, kathgod commented on internal/logic/authentication.go
> +		return 400
Это код внутри логической части хэндлера, тут не обязательно возвращать через константы пакета http

2023-12-16 16:06 UTC, kathgod commented on internal/logic/authorization.go
> +package logic
Оно отражает, это пакет логики для хендлеров

2023-12-16 16:16 UTC, kathgod commented on internal/logic/authorization.go
> +var secretKey = []byte(os.Getenv("PASETO_SECRET_KEY"))
а где мне тогда взять secretKey?

2023-12-16 16:49 UTC, Karzoug commented on internal/app/handler
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Пример возврата ошибки, он есть в апи:
```
{
  "code": 0,
  "message": "The server encountered a problem and could not process your request"
}
```

2023-12-16 16:50 UTC, Karzoug commented on internal/logic/authorization.go
> +	expirationTime := time.Now().Add(1 * time.Hour)
Оно должно быть в конфиге. Там ему выставить по-умолчанию часов 8-10.

2023-12-16 16:51 UTC, Karzoug commented on internal/logic/authorization.go
> +var secretKey = []byte(os.Getenv("PASETO_SECRET_KEY"))
В структуре конфига.

2023-12-16 16:54 UTC, Karzoug commented on internal/app/handler
> +	json.NewEncoder(w).Encode(response)
в 43 строке

2023-12-16 16:55 UTC, kathgod commented on internal/logic/authorization.go
> +var secretKey = []byte(os.Getenv("PASETO_SECRET_KEY"))
какого конфига? где мне его брать

2023-12-16 17:32 UTC, Karzoug commented on internal/app/handler
> +func (s *server) Authorization(w http.ResponseWriter, r *http.Request) {
1. Авторизация - проверка прав пользователя на совершение действий. Ее в коде нет вообще. У меня нет возражений, что она не реализована, у меня есть возражения, что код, который занимается аутентификацией, называется авторизацией. Положим HR не имеет прав на удаление/создание/редактирование сотрудника, как этот код это разграничивает?
2. В рамках МВП нам требуется: 1. получить логин-пароль и выдать токен 2. запретить доступ пользователя к путям, для которых нужна авторизация. Вторая задача решается через middleware.

2023-12-16 17:33 UTC, Karzoug commented on internal/logic/authentication.go
> +		return 400
Если не нравятся константы пакета http можно определить свои уровня пакета, но не писать в коде просто "400".

2023-12-16 17:55 UTC, kathgod commented on internal/app/handler
> +func (s *server) Authentication(w httpResponseWriter, r *http.Request) {
структура в Сашином коде

2023-12-16 17:55 UTC, PaulYakow commented on internal/logic/authorization.go
> +var secretKey = []byte(os.Getenv("PASETO_SECRET_KEY"))
Он добавлен в internal/config. По необходимости добавляем переменные туда.

2023-12-16 18:00 UTC, Karzoug commented on internal/app/handler
> +func (s *server) Authentication(w httpResponseWriter, r *http.Request) {
Ты в гите создала ветку от main, не от develop. В этом ключевая проблема.

2023-12-16 18:13 UTC, PaulYakow commented on internal/logic/authorization.go
> +package logic
Для хэндлеров обычно используется пакет controller. Но там прописываются в том числе и маршруты.
У нас это находится в internal/server. В частности маршрут /login находится в файле https://github.com/Employee-s-file-cabinet/backend/blob/develop/internal/server/auth.go

2023-12-17 10:40 UTC, kathgod commented on internal/logic/authorization.go
> +func CheckPassword(password, hashedPassword string) error {
Это на будущее. Может понадобится ее экспортировать.

2023-12-17 10:40 UTC, kathgod commented on internal/logic/authorization.go
> +func HashPassword(password string) (string, error) {
Это на будущее. Может понадобится ее экспортировать.

2023-12-17 11:09 UTC, kathgod commented on internal/logic/authorization.go
> +	DBDSN := fmt.Sprintf("user=%s password=%s host=%s port=%s dbname=%s sslmode=disable", dbUser, dbPassword, dbHost, dbPort, dbName)
Пока нет конфига в девелопе переделать не смогу.

2023-12-19 03:41 UTC, PaulYakow commented
Закрою: есть новый PR по этому функционалу от актуальной ветки

2023-12-19 03:41 UTC, closed without merging