Feature/authentication
Employee-s-file-cabinet/backend pull request #24
Opened 2023-12-22 08:19 UTC by PaulYakow

2023-12-22 11:30 UTC, rktkov approved these changes

2023-12-22 11:30 UTC, rktkov commented on internal/utils/token/paseto_maker.go
> +	"github.com/o1egl/paseto"
Отличный подход, использовать готовую библиотеку!

2023-12-22 11:30 UTC, rktkov commented on internal/server/handlers/auth.go
> +	authnData, err := h.dbRepository.GetAuthnData(ctx, auth.Login)
Вот тут видно, что обработчик начинает обрастать бизнес-логикой. Пока ее не много и она прямолинейна, можно оставить здесь. Но стоит уже задумываться, о создании слоя сервиса (реализация бизнес-логику), к которому обработчик бы обращался. Почему стоит замумываться, сейчас функционал обработчика выглядит так:
1. обработать входные аргументы запроса
2. провалидировать их
3. забрать данные из БД
4. проверить логическое условие
5. выполнить действие
Еще один шаг и будет много.
В какую сторону думать - сервис авторизации.

2023-12-22 11:38 UTC, PaulYakow commented on internal/server/handlers/auth.go
> +	authnData, err := h.dbRepository.GetAuthnData(ctx, auth.Login)
Благодарю за подтверждение - уже приходила такая мысль, что скоро придётся выделять сервисы/usecase

2023-12-22 21:21 UTC, Karzoug requested changes

2023-12-22 21:21 UTC, Karzoug commented on internal/storage/db/postgresql/authn.go
> +where work_email=$1;`
А почему бы просто не хранить email в "authorizations"? 
Не настаиваю.
В таком случае этот пользователь вообще не обязан быть сотрудником.

2023-12-22 21:21 UTC, Karzoug commented on internal/utils/password/password.go
> +type Password struct{}
Не понимаю назначения этого типа.

Я ожидал здесь увидеть, например:
```
type Password string
```

2023-12-22 21:21 UTC, Karzoug commented on internal/utils/password/password.go
> +func (p Password) Hash(password string) (string, error) {
Зачем здесь метод? Вызов извне функции
```
password.Hash(psw)
```
был бы тоже неплох.

2023-12-22 21:21 UTC, Karzoug commented on internal/utils/test/random.go
> +	rand.New(rand.NewSource(time.Now().UnixNano()))
1. По-моему, здесь ошибка: rand.New возвращает новый генератор, а не устанавливает параметр глобальному.
2. С версии 1.20 инициализировать глобальный генератор [вообще не надо](https://pkg.go.dev/math/rand#Seed). Единственное исключение в тестах, когда нужна воспроизводимость результатов. Однако в данном случае параметр задан текущему времени, а значит такая цель не ставилась.

2023-12-23 11:16 UTC, PaulYakow commented on internal/server/handlers/auth.go
> +		serr.ErrorMessage(w, r, http.StatusForbidden, "Login failed; Invalid user ID or password", nil)
Да, там разделю проверки: на то что пустые строки получены из БД и остальные ошибки от БД.
Ошибки тоже отдельно вынесу👍

2023-12-23 14:59 UTC, PaulYakow commented on internal/server/handlers/interface.go
> +type TokenManagement interface {
Согласен, переименую.
На счёт п.2 - думал это соглашение про интерфейсы с одним методом.

2023-12-23 15:02 UTC, PaulYakow commented on internal/storage/db/postgresql/authn.go
> +where work_email=$1;`
Так было изначально, когда логин был отдельным понятием от почты. Подумал раз почта всё равно хранится в таблице у пользователя, то поле логина просто удалил из таблицы авторизации.

2023-12-23 15:07 UTC, PaulYakow commented on internal/utils/password/password.go
> +func (p Password) Hash(password string) (string, error) {
Реализация интерфейса `PasswordVerification `

2023-12-23 15:15 UTC, PaulYakow commented on internal/utils/password/password.go
> +type Password struct{}
При необходимости структуру можно дополнить полями.
Ну и разница в размере пустой структуры и пустой строки - мелочь конечно, но есть. Если я конечно правильно понимаю)

2023-12-23 15:24 UTC, PaulYakow commented on internal/utils/test/random.go
> +	rand.New(rand.NewSource(time.Now().UnixNano()))
Кстати, да. Там стоял Seed до этого и я похоже неправильно понял что было написано в описании deprecated. Сейчас ещё раз перечитал - исправлюсь)

2023-12-23 16:17 UTC, Karzoug commented on internal/server/handlers/interface.go
> +type TokenManagement interface {
> На счёт п.2 - думал это соглашение про интерфейсы с одним методом.

Ты прав, так и есть, слабый аргумент с моей стороны. Поэтому их и два!)

2023-12-25 07:04 UTC, OlesyaNovikova approved these changes

2023-12-25 17:29 UTC, PaulYakow commented
Имеется более актуальная ветка для PR

2023-12-25 17:29 UTC, closed without merging