Add test data
Employee-s-file-cabinet/backend pull request #56
Opened 2024-01-11 14:07 UTC by dlc-01

2024-01-11 14:26 UTC, PaulYakow commented on migrations/test/init_data_for_test.sql
> +INSERT INTO public.trainings (id, user_id, title_of_institution, title_of_program, cost, date_begin, date_end, created_at, updated_at)
Аналогично по created_at, updated_at

2024-01-11 14:39 UTC, PaulYakow commented on migrations/test/init_data_for_test.sql
> +       (4, 'Офисный сотрудник', 'Выполняет ежедневные офисные и административные задачи.', '2023-01-10 12:26:13.845188', '2024-01-10 12:26:13.845188'),
Эта таблица о типах работ - например совместительство, основное место, временная, сезонная, работа на дому, государственная служба, дистанционный формат.

2024-01-11 15:10 UTC, Karzoug reviewed
Спасибо за помощь с данными!

Совет: primary key типа serial в postgres лучше вообще не заполнять, он сам автоинкрементируется. Можно потом натолкнуться на конфликт id-шников позже.

2024-01-11 16:50 UTC, Karzoug requested changes

2024-01-11 16:50 UTC, Karzoug commented on migrations/test/init_data_for_test.sql
> +VALUES (1, 'Капитан', 'Операции', 'Медицинские войска', 'А'),
**rank**: если все же А или Б, то стоит писать полностью с цифрой - А1, Б3
**title_of_commissariat**: это название комиссариата, пример: "Военный комиссариат Петроградского района г. Санкт-Петербурга" 
**specialty**: [ВУС](https://ru.wikipedia.org/wiki/%D0%92%D0%BE%D0%B5%D0%BD%D0%BD%D0%BE-%D1%83%D1%87%D1%91%D1%82%D0%BD%D0%B0%D1%8F_%D1%81%D0%BF%D0%B5%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%8C), пример: "101182"

2024-01-11 16:50 UTC, Karzoug commented on migrations/test/init_data_for_test.sql
> +        (31, '$2a$12$rrNnco5DWbaFxKMq457MouwkzL/R2XFoe1MrpoX9bN0ms09Zgk6ee', 1),
Предлагаю пока что оставить админа в единственном числе.

2024-01-11 16:50 UTC, Karzoug commented on migrations/test/init_data_for_test.sql
> +        (10, 'Грибов', 'Захар', 'Вениаминович', 'Мужской', '1956-09-09', 'г. Норильск', 4, 3, '3', '{"mobile": "+79215511436"}', 'gribov@company.com', 'Россия, г. Салават, Молодежный пер., д. 12 кв.1
"mobile": "+79215511436" -> "mobile": "79215511436"

2024-01-11 21:17 UTC, Karzoug commented on migrations/test/init_data_for_test.sql
> +VALUES (1, 'Капитан', 'Операции', 'Медицинские войска', 'А'),
Я не прав. Исправил комментарий, извиняюсь.

2024-01-11 22:49 UTC, Karzoug approved these changes

2024-01-11 23:02 UTC, Karzoug requested changes
Почти все :)

2024-01-11 23:32 UTC, dlc-01 commented on migrations/test/init_data_for_test.sql
> +INSERT INTO public.passports (user_id, series, number, issued_date, issued_by)
тип паспорта тоже добавить?

2024-01-12 07:33 UTC, Karzoug commented on migrations/test/init_data_for_test.sql
> +INSERT INTO public.passports (user_id, series, number, issued_date, issued_by)
Точно! Упустил я. Да, надо конечно.

2024-01-12 09:26 UTC, Karzoug approved these changes
Надо пробовать запускать, на беглый взгляд хорошо.

2024-01-12 09:51 UTC, dlc-01 commented
> Надо пробовать запускать, на беглый взгляд хорошо.

Да, я тестил каждые разы перед отправкой, все работало.

2024-01-12 11:11 UTC, PaulYakow approved these changes
Огонь!👍

Добавил ещё новых пользователей в политики доступа.

2024-01-12 11:37 UTC, merged