db migrations
Employee-s-file-cabinet/backend pull request #7
Opened 2023-12-11 11:24 UTC by PaulYakow

Для удобства проверки добавил docker-compose файл (с описанием тестовой БД) и команды в Makefile.

2023-12-11 20:17 UTC, OlesyaNovikova approved these changes

2023-12-15 06:26 UTC, Karzoug requested changes
Хорошя работа! Хотелось бы услышать комментарии на мои замечания

2023-12-15 06:51 UTC, PaulYakow commented on internal/db/migrations/000001_init_schema.up.sql
> +    "place_of_birth"       date    NOT NULL,
Исправил

2023-12-15 06:52 UTC, PaulYakow commented on internal/db/migrations/000001_init_schema.up.sql
> +    "fee_to_tax"          integer NOT NULL,
Согласен. Исправил.

2023-12-15 06:56 UTC, PaulYakow commented on internal/db/migrations/000001_init_schema.up.sql
> +    "document_number"     varchar NOT NULL,
Точно! Добавил "name_of_program" по аналогии с таблицей обучения.

2023-12-15 06:57 UTC, PaulYakow commented on internal/db/migrations/000001_init_schema.up.sql
> +    "number"        integer       NOT NULL,
Согласен. Исправил.

2023-12-15 07:06 UTC, PaulYakow commented on internal/db/migrations/000001_init_schema.up.sql
> +    "salary"              integer NOT NULL,
Согласен. Исправил на bigint (почитал про money - решил пока не экспериментировать).

2023-12-15 07:07 UTC, PaulYakow commented on internal/db/migrations/000001_init_schema.up.sql
> +    "user_id"       bigint  NOT NULL,
Не совсем понял - у нас же HR/рекрутер в любом случае является сотрудником компании🤔

2023-12-15 09:01 UTC, merged